
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Zigic
 */
public class VistaPrevia extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrevia
     */
    public VistaPrevia() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/logo.jpg")).getImage());
        this.getContentPane().setBackground(Color.getHSBColor(138, 40, 77));
        ArrayList<JEditorPane> aux2 = principal.panes;
        BufferedImage bi = new BufferedImage(1030,400,BufferedImage.TYPE_INT_RGB);
        ArrayList<JLabel> aux = new ArrayList<>();
        for (int p = 0; p < aux2.size(); p++){
            JLabel aux3 = new JLabel();
            aux2.get(p).paint(bi.getGraphics());
            aux3.setIcon(new ImageIcon(bi.getScaledInstance(250, 250, BufferedImage.SCALE_DEFAULT)));
            bi = new BufferedImage(1030,400,BufferedImage.TYPE_INT_RGB);
            aux.add(aux3);
        }
        int lenght = aux.size();
        lenght = lenght/3;
        int cont = 0;
        if (aux.size()== 1){
            for (int i = 0; i< 1; i++){
                for (int j = 0; j<1; j++){
                    JLabel vista = aux.get(cont);
                    vista.setVisible(true);
                    vista.setSize(250,250);
                    vista.setLocation(i*275+10, j*275+10);
                    this.add(vista);
                    this.repaint();
                    cont++;
                }
            }
        } else if (aux.size() == 2){
            for (int i = 0; i< 2; i++){
                for (int j = 0; j<1; j++){
                    JLabel vista =aux.get(cont);
                    vista.setVisible(true);
                    vista.setSize(250,250);
                    vista.setLocation(i*275+10, j*275+10);
                    this.add(vista);
                    this.repaint();
                    cont++;
                }
            }
        } else if (aux.size() == 3){
            for (int i = 0; i< 3; i++){
                for (int j = 0; j<1; j++){
                    JLabel vista =aux.get(cont);
                    vista.setVisible(true);
                    vista.setSize(250,250);
                    vista.setLocation(i*275+10, j*275+10);
                    this.add(vista);
                    this.repaint();
                    cont++;
                }
            }
        } else {
            for (int i = 0; (i<lenght+1); i++){
                for (int j = 0; (j<3)&&(cont<aux.size()); j++){
                    JLabel vista =aux.get(cont);
                    vista.setVisible(true);
                    vista.setSize(250,250);
                    vista.setLocation(j*275+10, i*275+10);
                    this.add(vista);
                    this.repaint();
                    cont++;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar2 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 813, Short.MAX_VALUE)
                .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrevia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrevia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrevia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrevia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrevia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar jScrollBar2;
    // End of variables declaration//GEN-END:variables
}
